version: "3.8"
services:
  # MySQL database service
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root password for MySQL
      MYSQL_DATABASE: medilab_db  # Create this database
      MYSQL_USER: user  # MySQL user
      MYSQL_PASSWORD: userpassword  # Password for MySQL user
    ports:
      - "3306:3306"  # Expose MySQL port
    networks:
      - medilab-network
    volumes:
      - mysql-data:/var/lib/mysql  # Persist data in a Docker volume

  # Aggregator Service
  aggregator-service:
    build: ./aggregator-service
    container_name: aggregator-service
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/medilab_db  # Connecting to medilab_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    ports:
      - "8084:8084"  # Expose to host machine
    networks:
      - medilab-network

  # Appointment Service
  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/medilab_db  # Connecting to medilab_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    ports:
      - "8082:8082"  # Expose to host machine
    networks:
      - medilab-network

  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/medilab_db  # Connecting to medilab_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    ports:
      - "8083:8083"  # Expose to host machine
    networks:
      - medilab-network

  # Patient Service
  patient-service:
    build: ./patient-service
    container_name: patient-service
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/medilab_db  # Connecting to medilab_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    ports:
      - "8081:8081"  # Expose to host machine
    networks:
      - medilab-network

networks:
  medilab-network:
    driver: bridge

volumes:
  mysql-data:  # Volume for persistent storage of MySQL data
